// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package wasm

import (
	"cuelang.org/go/internal/core/adt"
	"cuelang.org/go/internal/pkg"
)

func init() {
	pkg.Register("wasm", p)
}

var _ = adt.TopKind // in case the adt package isn't used

var p = &pkg.Package{
	Native: []*pkg.Builtin{
		{
			Name: "TransformStringByFile",
			Params: []pkg.Param{
				{Kind: adt.StringKind},
				{Kind: adt.StringKind},
				{Kind: adt.StringKind},
			},
			Result: adt.StringKind,
			Func: func(c *pkg.CallCtxt) {
				wasmFile := c.String(0)
				function := c.String(1)
				s := c.String(2)
				if c.Do() {
					c.Ret, c.Err = ExecuteFile(wasmFile, function, s)
				}
			},
		},
		{
			Name: "TransformStringByUrl",
			Params: []pkg.Param{
				{Kind: adt.StringKind},
				{Kind: adt.StringKind},
				{Kind: adt.StringKind},
			},
			Result: adt.StringKind,
			Func: func(c *pkg.CallCtxt) {
				wasmFile := c.String(0)
				function := c.String(1)
				s := c.String(2)
				if c.Do() {
					c.Ret, c.Err = ExecuteUrl(wasmFile, function, s)
				}
			},
		},
	},
}
