// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package wasm

import (
	"cuelang.org/go/internal/core/adt"
	"cuelang.org/go/internal/pkg"
)

func init() {
	pkg.Register("wasm", p)
}

var _ = adt.TopKind // in case the adt package isn't used

var p = &pkg.Package{
	Native: []*pkg.Builtin{
		{
			Name: "TransformValueByFile",
			Params: []pkg.Param{
				{Kind: adt.StringKind},
				{Kind: adt.StringKind},
				{Kind: adt.TopKind},
			},
			Result: adt.TopKind,
			Func: func(c *pkg.CallCtxt) {
				wasmFile := c.String(0)
				function := c.String(1)
				v := c.Value(2)
				if c.Do() {
					c.Ret, c.Err = TransformValueByFile(wasmFile, function, v)
				}
			},
		},
		{
			Name: "TransformValueByUrl",
			Params: []pkg.Param{
				{Kind: adt.StringKind},
				{Kind: adt.StringKind},
				{Kind: adt.TopKind},
			},
			Result: adt.TopKind,
			Func: func(c *pkg.CallCtxt) {
				wasmFile := c.String(0)
				function := c.String(1)
				v := c.Value(2)
				if c.Do() {
					c.Ret, c.Err = TransformValueByUrl( wasmFile, function, v)
				}
			},
		},
	},
}
